/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Cocoa/Cocoa.h>

@class NSImage;

@interface BBHoverButton : NSControl
{
    NSImage *_hoverImage;
    NSImage *_alternateImage;
    NSImage *_image;
    BOOL _mouseInside;
    BOOL _mouseDown;
    int _trackingRectTag;
    struct _NSRect _lastFrame;
    SEL _action;
    id _target;
}

- (id)init;
- (SEL)action;
- (id)target;
- (void)setAction:(SEL)fp8;
- (void)setTarget:(id)fp8;
- (void)dealloc;
- (void)sizeToFit;
- (void)calculateTrackingRect;
- (void)drawRect:(struct _NSRect)fp8;
- (void)viewDidMoveToWindow;
- (void)mouseEntered:(NSEvent*)fp8;
- (void)mouseExited:(NSEvent*)fp8;
- (void)mouseDown:(NSEvent*)fp8;
- (void)mouseDragged:(NSEvent*)fp8;
- (BOOL)mouseDownCanMoveWindow;
- (void)mouseUp:(NSEvent*)fp8;
- (void)setAlternateImage:(NSImage*)fp8;
- (void)setImage:(NSImage*)fp8;
- (void)setHoverImage:(NSImage*)fp8;

@end

