/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Cocoa/Cocoa.h>

@interface BBMessage : NSObject <NSCoding>
{
    NSString *_emlxFile;
    NSDictionary *_headers;
    NSAttributedString *_body;
    NSString *_mailbox;
    NSString *_uncommentedSender;
}

- (id)replacementObjectForPortCoder:(NSPortCoder*)fp8;
- (void)encodeWithCoder:(NSCoder*)fp8;
- (id)initWithCoder:(NSCoder*)fp8;
- (void)dealloc;
- (NSString*)description;
- (NSString*)mailbox;
- (NSString*)emlxFile;
- (NSDictionary*)headers;
- (NSAttributedString*)body;
- (NSString*)uncommentedSender;
- (void)setMailbox:(NSString*)fp8;
- (void)setEmlxFile:(NSString*)fp8;
- (void)setHeaders:(NSDictionary*)fp8;
- (void)setBody:(NSAttributedString*)fp8;
- (void)setUncommentedSender:(NSString*)fp8;

@end

