/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Cocoa/Cocoa.h>

@interface BBNotificationPanel : NSPanel
{
    BOOL _fading;
}

- (id)initWithContentRect:(NSRect)fp8 styleMask:(NSUInteger)fp24 backing:(NSBackingStoreType)fp28 defer:(BOOL)fp32;
- (void)_faded;
- (void)_performFade;
- (void)show;
- (void)fade;
- (void)becomeKeyWindow;
- (void)becomeMainWindow;
- (BOOL)canBecomeKeyWindow;
- (void)mouseEntered:(id)fp8;
- (void)mouseExited:(id)fp8;
- (BOOL)canBecomeMainWindow;
- (void)display;
- (BOOL)isOpaque;
- (BOOL)acceptsFirstMouse:(id)fp8;

@end

