/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Cocoa/Cocoa.h>

#import "BBNotificationServerProtocol-Protocol.h"
#import "BBWindowController.h"
#import "BBMessage.h"

@interface BBNotificationServer : NSObject <BBNotificationServerProtocol>
{
    id _target;
    NSMutableArray *_messages;
    int _currentMessage;
    BOOL _idle;
    BBWindowController *_windowController;
}

+ (void)initialize;
- (oneway void)setCallbackTarget:(id)fp8;
- (void)updateCounter;
- (void)showNextMessage;
- (void)notificationPanelAction:(int)fp8;
- (void)notificationPanelNextMessage;
- (void)notificationPanelDidFade;
- (oneway void)setPreferencesMode:(BOOL)fp8;
- (oneway void)showNotificationForMessage:(BBMessage*)fp8;
- (oneway void)setLocalizedHeaders:(in bycopy id)fp8;
- (oneway void)setLocalizedNoSubject:(in bycopy id)fp8;
- (oneway void)setEnabled:(BOOL)fp8;
- (oneway void)setTransparency:(in float)fp8;
- (oneway void)setQuotationLevels:(in int)fp8;
- (oneway void)setDismissAfter:(in int)fp8;
- (oneway void)setCustomHeaders:(in bycopy id)fp8;
- (oneway void)setHeaderDetail:(in int)fp8;
- (oneway void)setExcludedMailboxes:(in bycopy id)fp8;
- (oneway void)setMailboxDetail:(in int)fp8;
- (oneway void)setShowHeaderTitles:(BOOL)fp8;
- (oneway void)setShowMailbox:(BOOL)fp8;
- (oneway void)setHideInMail:(BOOL)fp8;
- (oneway void)setFontFamily:(NSString*)fp8 size:(float)fp12;
- (oneway void)setOpenInSeparateWindow:(BOOL)fp8;
- (BOOL)openInSeparateWindow;
- (id)customHeaders;
- (id)excludedMailboxes;
- (float)transparency;
- (int)quotationLevels;
- (int)headerDetail;
- (int)mailboxDetail;
- (NSString*)fontFamily;
- (float)fontSize;
- (BOOL)enabled;
- (int)dismissAfter;
- (BOOL)showHeaderTitles;
- (BOOL)showMailbox;
- (BOOL)hideInMail;
- (void)readDefaults;
- (void)connectionDidDie:(id)fp8;
- (void)workspaceDidTerminateApplication:(NSNotification*)fp8;
- (id)init;
- (NSApplicationTerminateReply)applicationShouldTerminate:(NSApplication*)fp8;
- (void)dealloc;

@end

