/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */
#import "BBMessage.h"

@protocol BBNotificationServerProtocol
- (oneway void)setCallbackTarget:(id)fp8;
- (oneway void)showNotificationForMessage:(BBMessage*)fp8;
- (oneway void)setLocalizedHeaders:(in bycopy id)fp8;
- (oneway void)setLocalizedNoSubject:(in bycopy id)fp8;
- (oneway void)setPreferencesMode:(in char)fp8;
- (oneway void)setEnabled:(in char)fp8;
- (oneway void)setTransparency:(in float)fp8;
- (oneway void)setQuotationLevels:(in int)fp8;
- (oneway void)setDismissAfter:(in int)fp8;
- (oneway void)setCustomHeaders:(in bycopy id)fp8;
- (oneway void)setHeaderDetail:(in int)fp8;
- (oneway void)setExcludedMailboxes:(in bycopy id)fp8;
- (oneway void)setMailboxDetail:(in int)fp8;
- (oneway void)setShowHeaderTitles:(in char)fp8;
- (oneway void)setShowMailbox:(in char)fp8;
- (oneway void)setHideInMail:(in char)fp8;
- (oneway void)setFontFamily:(in bycopy id)fp8 size:(in float)fp12;
- (oneway void)setOpenInSeparateWindow:(in char)fp8;
- (BOOL)enabled;
- (int)dismissAfter;
- (BOOL)showHeaderTitles;
- (BOOL)showMailbox;
- (BOOL)hideInMail;
- (float)transparency;
- (int)quotationLevels;
- (id)customHeaders;
- (int)headerDetail;
- (id)excludedMailboxes;
- (int)mailboxDetail;
- (NSString*)fontFamily;
- (float)fontSize;
- (BOOL)openInSeparateWindow;
@end

