/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Cocoa/Cocoa.h>

@interface BBResizeView : NSView
{
    NSImage *_resizeIndicator;
}

- (id)initWithFrame:(struct _NSRect)fp8;
- (void)drawRect:(struct _NSRect)fp8;
- (void)mouseUp:(NSEvent*)fp8;
- (void)mouseDown:(NSEvent*)fp8;
- (BOOL)mouseDownCanMoveWindow;

@end

