/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Cocoa/Cocoa.h>
#import <AddressBook/AddressBook.h>
#import "BBBezelView.h"
#import "BBMessage.h"

@interface BBWindowController : NSWindowController <ABImageClient>
{
    BBBezelView *_mainView;
    int _trackingRectTag;
    struct _NSPoint _lastMouseDownLocation;
    id delegate;
    BOOL _cancelFade;
    int _imageTag;
    BOOL _preferencesMode;
}

- (void)consumeImageData:(NSData*)fp8 forTag:(NSInteger)fp12;
- (void)setBackgroundColor:(NSColor*)fp8;
- (void)setCounter:(id)fp8;
- (void)setPreferencesMode:(BOOL)fp8;
- (void)setTransparency:(float)fp8;
- (void)setQuotationLevels:(int)fp8;
- (void)setDismissAfter:(int)fp8;
- (void)setHeaders:(NSArray*)fp8;
- (void)setShowHeaderTitles:(BOOL)fp8;
- (void)setShowMailbox:(BOOL)fp8;
- (void)setFontFamily:(NSString*)fp8 size:(float)fp12;
- (void)showMessage:(BBMessage*)fp8;
- (void)awakeFromNib;
- (void)windowDidResize:(NSNotification*)fp8;
- (void)mouseDown:(NSEvent*)fp8;
- (void)fade;
- (void)timeout;
- (void)click:(id)fp8;
- (void)mouseUp:(NSEvent*)fp8;

@end

