/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import <Cocoa/Cocoa.h>

@interface NSBezierPath (MailAppetizerAdditions)
+ (id)bezierPathWithRoundedRect:(NSRect)fp8 radius:(float)fp24;
@end

