// _BBNotificationServer_EOArchive_English.java
// Generated by EnterpriseObjects palette at Montag, 4. Juli 2005 15:13 Uhr Europe/Berlin

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _BBNotificationServer_EOArchive_English extends com.webobjects.eoapplication.EOArchive {
    BBBezelView _nsCustomView0;
    BBNotificationServer _bBNotificationServer0;
    BBWindowController _bBWindowController0;
    com.webobjects.eointerface.swing.EOFrame _eoFrame0;
    javax.swing.JPanel _nsView0;

    public _BBNotificationServer_EOArchive_English(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();


        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "delegate")) != null)) {
            _bBNotificationServer0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (BBNotificationServer)replacement;
            _replacedObjects.setObjectForKey(replacement, "_bBNotificationServer0");
        } else {
            _bBNotificationServer0 = (BBNotificationServer)_registered(new BBNotificationServer(), "BBMessageServer");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "delegate._windowController")) != null)) {
            _bBWindowController0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (BBWindowController)replacement;
            _replacedObjects.setObjectForKey(replacement, "_bBWindowController0");
        } else {
            _bBWindowController0 = (BBWindowController)_registered(new BBWindowController(), "BBWindowController");
        }

        _nsCustomView0 = (BBBezelView)_registered(new BBBezelView(), "View");
        _eoFrame0 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "Panel");
        _nsView0 = (JPanel)_eoFrame0.getContentPane();
    }

    protected void _awaken() {
        super._awaken();

        if (_replacedObjects.objectForKey("_bBNotificationServer0") == null) {
            _connect(_owner(), _bBNotificationServer0, "delegate");
        }
    }

    protected void _init() {
        super._init();
        _connect(_eoFrame0, _bBWindowController0, "delegate");

        if (_replacedObjects.objectForKey("_bBWindowController0") == null) {
            _connect(_bBWindowController0, _eoFrame0, "window");
        }

        if (_replacedObjects.objectForKey("_bBNotificationServer0") == null) {
            _connect(_bBNotificationServer0, _bBWindowController0, "_windowController");
        }

        if (_replacedObjects.objectForKey("_bBWindowController0") == null) {
            _connect(_bBWindowController0, _bBNotificationServer0, "delegate");
        }

        if (_replacedObjects.objectForKey("_bBWindowController0") == null) {
            _connect(_bBWindowController0, _nsCustomView0, "_mainView");
        }

        if (!(_nsView0.getLayout() instanceof EOViewLayout)) { _nsView0.setLayout(new EOViewLayout()); }
        _nsCustomView0.setSize(300, 390);
        _nsCustomView0.setLocation(-7, -6);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsCustomView0, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsView0.add(_nsCustomView0);
        _nsView0.setSize(286, 378);
        _eoFrame0.setTitle("");
        _eoFrame0.setLocation(531, 361);
        _eoFrame0.setSize(286, 378);
    }
}
